### ISSUE TITLE
Open file/folder by clicking on preview/filename/path

### ISSUE THREAD

**Issue by jancborchardt** [keeporsweep/keeporsweep-desktop#7]
To check out a bigger view of the file (and others nearby), it would be nice if:

- [ ] Clicking on preview and filename opens the file in the proper viewer or app for it
- [ ] Clicking the path opens the folder where the file is in, ideally with the file highlighted (if that’s at all possible)

**Comment by prashantsengar** [comment]
What if we just add 2 more buttons to open the folder or file?

**Comment by jancborchardt** [comment]
Thanks again for your contribution @prashantsengar! :)
